#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed
#four million, find the sum of the even-valued terms.

fib_list = [1,2]
sum = 0

while fib_list[-1] + fib_list[-2] < (4 * 10**6):
    new_entry = fib_list[-1] + fib_list[-2]
    fib_list.append(new_entry)

for n in fib_list:
    if n % 2 == 0:
        sum += n

print(sum)
